### ISSUE TITLE
過去のログデータを表示するデモモードの実装

### ISSUE THREAD

**Issue by dynamis** [webdino/enocean-console-demo#1]
サーバ側の REST API で取得したログデータをローカルの JSON ファイルとして保存しておき、サーバに接続できないときはそのデータを表示し続けることで、クライアント単体での動作をする

- [x] モード切り替えボタンを作る (WS 接続試みて繋がらなかったらデモモードで開始、デモモード中もサーバ接続できていたらデータは受け取り続ける)
- [x] JSON データからの読み込みに対応する
  - [x]  query string での指定に対応
- [x] サンプル JSON データを揃える
- [x] JSON データの古い方を最初に読み込んで、その後のデータは定期的に読み込んでるように見せる
- [x] デモデータが古いデータの場合 (ほぼ常に)、直近の 1, 10 分, 1 時間で絞り込むデータが存在しなくてエラーになる (採集データの時刻を基準にするなどの挙動に帰る必要がある)

**Comment by epli2** [comment]
主に以下のコミットにて、デモモード対応を行った

* デモモードの追加 https://github.com/webdino/enocean-console-demo/commit/133cf5c7d6cdd8187002be1d2881d14cdbbf9bf9
* 範囲指定ボタンを変更  https://github.com/webdino/enocean-console-demo/commit/8d34e84a28118e175812137c2f8ab682a547af81
* デモデータ追加  https://github.com/webdino/enocean-console-demo/commit/06beb1e8dee424b29017f750595eb305afbc92f5
* 任意のデモ用ファイル名を指定できるように  https://github.com/webdino/enocean-console-demo/commit/04997c8b9eac109910e6d4ca9cf96c0f0a597a3a
